# Generated by Django 4.2.2 on 2023-06-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
