# Generated by Django 4.2.2 on 2023-06-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
    ]
